---
- hosts: localhost

  vars:
    vim_version: v8.2.2600
    HOME: "{{ ansible_env.HOME }}"

  roles:
    - role: vim-build
      tags:
        - build
    - role: vim-config
      tags:
        - config
