- name: vim blank dirs
  file:
    path: "{{ HOME }}/.vim/{{ item }}"
    state: directory
  loop: "{{ blank_dirs }}"

- name: vimplug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ HOME }}/.vim/autoload/plug.vim"

- name: link vim dirs
  file:
    dest: "{{ HOME }}/.vim/{{ item }}"
    src: "{{ playbook_dir }}/../dot-vim/{{ item }}"
    state: link
  loop: "{{ link_dirs }}"

- name: vim rc files
  file:
    dest: "{{ HOME }}/.{{ item }}imrc"
    src: "{{ playbook_dir }}/../dot-{{ item }}imrc"
    state: link
  loop:
    - v
    - gv

- name: install plugins with vim-plug
  shell: vim -c PlugUpdate -c qa > /dev/null
